component: website
name: site

inputs:
  # React application. "hook" runs before deployment to build the source code.  "dist" is the built artifact directory which is uploaded.
  src:
    src: ./
    hook: npm run build
    dist: build
  env:
    API_HOST: ${env:API_HOST}
  # Enable this when you want to set a custom domain.
  # domain: ${env:domain} 


